apiVersion: v1
kind: ConfigMap
metadata:
  name: st-test-nginx-config
data:

  # nginx script
  kubernetescurljob.sh: |
    #!/bin/env sh

    {{- if .Values.withCert }}
    echo "make a request to  curl $CURL_OPTIONS $URL/$ID_DOSSIER -H Token:$TOKEN --cert /certs/full_cert.pem"
    curl $CURL_OPTIONS "$URL/$ID_DOSSIER" -H "Token:$TOKEN" --cert /certs/full_cert.pem
    {{- else }}
    echo "make a request to  curl $CURL_OPTIONS $URL/$ID_DOSSIER -H Token:$TOKEN"
    curl $CURL_OPTIONS "$URL/$ID_DOSSIER" -H "Token:$TOKEN"
    {{- end }}
    echo "end request"
