apiVersion: batch/v1
kind: CronJob
metadata:
  name: st-test-nginx-cronjob
  labels:
    app: st-test-nginx-cronjob
    type: cron
spec:
  schedule: "* 1 * * *" # Run every hour
  suspend: true
  jobTemplate:
    metadata:
      labels:
        app: st-test-nginx-cronjob
        type: cron
    spec:
      template:
        spec:
          containers:
            - name: st-test-nginx-cronjob
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              env:
                - name: ID_DOSSIER
                  value: "{{ .Values.iddossier }}"
                - name: CURL_OPTIONS
                  value: "{{ .Values.curlOption }}"
                {{- if .Values.useProxy }}
                - name: HTTP_PROXY
                  value: "{{ .Values.proxyUrl }}"
                - name: HTTPS_PROXY
                  value: "{{ .Values.proxyUrl }}"
                {{- end }}
                - name: URL
                  value: "{{ .Values.url_to_test }}"
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: nginx-certs-secret
                      key: TOKEN
                - name: JWT_TOKEN_URL
                  value: "{{ .Values.jwtTokenUrl }}"
                - name: JWT_TOKEN_PRE_OPTS
                  value: "--location --request"
                - name: JWT_TOKEN_OPTS
                  value: "--header 'Content-Type: application/x-www-form-urlencoded' --data  'grant_type=client_credentials&scope=releve_information_integral:read' --user \"$JWT_USER\"  -k -vvv"
                - name: JWT_USER
                  valueFrom:
                    secretKeyRef:
                      name: nginx-certs-secret
                      key: JWT_USER
              command: 
                - /bin/sh
                - -c
                - {{ .Values.command }}
              volumeMounts:
                - name: script
                  mountPath: /scripts
                - name: certs
                  mountPath: /certs

              resources:
                requests:
                  cpu: 500m
                  memory: 100M
                limits:
                  cpu: 500m
                  memory: 100M

          volumes:
            - name: script
              configMap:
                name: {{ .Values.configmap.name}}
                defaultMode: 0777
            - name: certs
              secret:
                secretName: nginx-certs-secret
                defaultMode: 0777
          restartPolicy: Never