apiVersion: v1
kind: ConfigMap
metadata:
  name: st-test-nginx-config
data:

  # nginx script
  kubernetescurljob.sh: |
    #!/bin/env sh

    {{- if .Values.withCert }}
    echo "make a request to  curl -vvv $URL/$ID_DOSSIER -H Token:$TOKEN --cert /certs/cert.pem --key /certs/key.pem"
    curl -vvv "$URL/$ID_DOSSIER" -H "Token:$TOKEN" --cert /certs/cert.pem --key /certs/key.pem
    {{- else }}
    echo "make a request to  curl -vvv $URL/$ID_DOSSIER -H Token:$TOKEN"
    curl -vvv "$URL/$ID_DOSSIER" -H "Token:$TOKEN"
    {{- end }}
    echo "end request"
