image:
  curl: badouralix/curl-jq-yq:ubuntu
  openssl: alpine/openssl:3.5.4
iddossier: api/demo/demo
url_to_test: https://www.google.fr
withCert: true
cronexpr: "* 1 * * *"
curlOption: "-vvv -k"
command: sh /scripts/kubernetescurljob.sh
secret:
  mount: testmj
  path: test-ines
useProxy: false
proxyUrl: http://proxy.example.com:8080
jwtTokenUrl: https://url.jwt.token/endpoint
configMap:
  name: st-test-nginx-config